# Generated by Django 5.0.14 on 2026-09-12 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cotisations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegleRelance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("libelle", models.CharField(max_length=120)),
                (
                    "decalage_jours",
                    models.IntegerField(
                        help_text="Négatif : avant l'échéance. Positif : après l'échéance."
                    ),
                ),
                (
                    "niveau",
                    models.CharField(
                        choices=[
                            ("INFORMATION", "Information"),
                            ("RAPPEL", "Rappel"),
                            ("RETARD", "Retard"),
                            ("RELANCE_1", "Relance 1"),
                            ("RELANCE_2", "Relance 2"),
                            ("ALERTE", "Alerte"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "destinataires",
                    models.CharField(
                        choices=[
                            ("MEMBRE", "Membre"),
                            ("MEMBRE_SECTION", "Membre et responsable de section"),
                            ("MEMBRE_FINANCIER", "Membre et responsable financier"),
                            ("RESPONSABLES", "Responsables uniquement"),
                        ],
                        default="MEMBRE",
                        max_length=20,
                    ),
                ),
                (
                    "gabarit_message",
                    models.CharField(
                        default="notifications/relance.txt", max_length=80
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("modifiee_le", models.DateTimeField(auto_now=True)),
                (
                    "modifiee_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "règle de relance",
                "verbose_name_plural": "règles de relance",
                "ordering": ["decalage_jours"],
            },
        ),
        migrations.CreateModel(
            name="Relance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_emission", models.DateTimeField(auto_now_add=True)),
                ("jours_ecart", models.IntegerField()),
                (
                    "cotisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="relances",
                        to="cotisations.cotisation",
                    ),
                ),
                (
                    "regle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="relances",
                        to="relances.reglerelance",
                    ),
                ),
            ],
            options={
                "verbose_name": "relance",
                "verbose_name_plural": "relances",
                "ordering": ["-date_emission"],
            },
        ),
        migrations.AddConstraint(
            model_name="relance",
            constraint=models.UniqueConstraint(
                fields=("cotisation", "regle"), name="unicite_relance_cotisation_regle"
            ),
        ),
    ]
