# Generated by Django 5.0.14 on 2026-09-12 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("membres", "0001_initial"),
        ("sections", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DemandeAdhesion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenoms", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("telephone", models.CharField(blank=True, max_length=20)),
                ("grade", models.CharField(blank=True, max_length=80)),
                ("etablissement", models.CharField(blank=True, max_length=150)),
                ("motivation", models.TextField(blank=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En attente"),
                            ("EN_EXAMEN", "En examen"),
                            ("INFOS_REQUISES", "Informations requises"),
                            ("VALIDEE", "Validée"),
                            ("REJETEE", "Rejetée"),
                        ],
                        default="EN_ATTENTE",
                        max_length=15,
                    ),
                ),
                ("motif", models.TextField(blank=True)),
                ("date_soumission", models.DateTimeField(auto_now_add=True)),
                ("date_traitement", models.DateTimeField(blank=True, null=True)),
                (
                    "membre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="demandes",
                        to="membres.membre",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="demandes",
                        to="sections.section",
                    ),
                ),
                (
                    "traitee_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "demande d'adhésion",
                "verbose_name_plural": "demandes d'adhésion",
                "ordering": ["-date_soumission"],
                "indexes": [
                    models.Index(
                        fields=["statut", "date_soumission"],
                        name="adhesions_d_statut_bc6902_idx",
                    )
                ],
            },
        ),
    ]
