# Generated by Django 5.0.14 on 2026-09-12 21:49

import apps.adhesions.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhesions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PieceJustificative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_piece', models.CharField(choices=[('CARTE_PROFESSIONNELLE', 'Carte professionnelle'), ('ATTESTATION_EMPLOI', "Attestation d'exercice ou d'emploi"), ('DIPLOME', 'Diplôme'), ('AUTRE', 'Autre document')], max_length=25)),
                ('fichier', models.FileField(upload_to=apps.adhesions.models.chemin_piece, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('depose_le', models.DateTimeField(auto_now_add=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='adhesions.demandeadhesion')),
            ],
            options={
                'verbose_name': 'pièce justificative',
                'verbose_name_plural': 'pièces justificatives',
                'ordering': ['depose_le'],
            },
        ),
    ]
