# Generated by Django 5.0.14 on 2026-09-12 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhesions', '0002_piecejustificative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeadhesion',
            name='etablissement',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='demandeadhesion',
            name='grade',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='demandeadhesion',
            name='motivation',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='demandeadhesion',
            name='telephone',
            field=models.CharField(max_length=20),
        ),
    ]
