# Generated by Django 5.0.14 on 2026-09-12 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("membres", "0001_initial"),
        ("relances", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("destinataire", models.CharField(max_length=150)),
                ("type", models.CharField(max_length=25)),
                (
                    "canal",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Courriel"),
                            ("INTERNE", "Notification interne"),
                        ],
                        default="EMAIL",
                        max_length=15,
                    ),
                ),
                ("objet", models.CharField(max_length=200)),
                ("gabarit", models.CharField(max_length=80)),
                ("contexte", models.JSONField(blank=True, default=dict)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En attente"),
                            ("ENVOYEE", "Envoyée"),
                            ("ECHEC", "Échec"),
                        ],
                        default="EN_ATTENTE",
                        max_length=12,
                    ),
                ),
                ("tentatives", models.PositiveSmallIntegerField(default=0)),
                ("derniere_erreur", models.CharField(blank=True, max_length=255)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("date_envoi", models.DateTimeField(blank=True, null=True)),
                (
                    "membre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="membres.membre",
                    ),
                ),
                (
                    "relance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="relances.relance",
                    ),
                ),
            ],
            options={
                "verbose_name": "notification",
                "verbose_name_plural": "notifications",
                "ordering": ["-cree_le"],
                "indexes": [
                    models.Index(
                        fields=["statut", "cree_le"],
                        name="notificatio_statut_27407f_idx",
                    )
                ],
            },
        ),
    ]
