# Generated by Django 5.0.14 on 2026-09-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='piece_jointe_generateur',
            field=models.CharField(blank=True, help_text="Chemin Python pointillé (ex. apps.cotisations.services.generer_recu_pdf) d'une fonction qui reçoit `contexte` et retourne (nom_fichier, contenu, type_mime) — régénérée à chaque tentative d'envoi plutôt que stockée, comme le corps du courriel lui-même (voir rendre_gabarit).", max_length=200),
        ),
    ]
