# Generated by Django 5.0.14 on 2026-09-12 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("membres", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cotisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exercice", models.PositiveIntegerField()),
                ("montant_du", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "montant_paye",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("date_emission", models.DateField(auto_now_add=True)),
                ("date_echeance", models.DateField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En attente"),
                            ("PARTIEL", "Partiellement payée"),
                            ("PAYEE", "Payée"),
                            ("EN_RETARD", "En retard"),
                            ("EXEMPTEE", "Exemptée"),
                        ],
                        default="EN_ATTENTE",
                        max_length=12,
                    ),
                ),
                (
                    "membre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cotisations",
                        to="membres.membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "cotisation",
                "verbose_name_plural": "cotisations",
                "ordering": ["-exercice", "membre__nom"],
            },
        ),
        migrations.CreateModel(
            name="Exemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exercice", models.PositiveIntegerField()),
                ("motif", models.CharField(max_length=200)),
                ("date_decision", models.DateField(auto_now_add=True)),
                (
                    "accordee_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "membre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exemptions",
                        to="membres.membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "exemption",
                "verbose_name_plural": "exemptions",
            },
        ),
        migrations.CreateModel(
            name="Paiement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("ESPECES", "Espèces"),
                            ("VIREMENT", "Virement bancaire"),
                            ("MOBILE_MONEY", "Monnaie électronique mobile"),
                            ("CHEQUE", "Chèque"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=60)),
                ("date_paiement", models.DateTimeField()),
                (
                    "cotisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paiements",
                        to="cotisations.cotisation",
                    ),
                ),
                (
                    "enregistre_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paiements_saisis",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "paiement",
                "verbose_name_plural": "paiements",
                "ordering": ["-date_paiement"],
            },
        ),
        migrations.AddIndex(
            model_name="cotisation",
            index=models.Index(
                fields=["statut", "date_echeance"], name="cotisations_statut_036bf6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cotisation",
            index=models.Index(
                fields=["exercice"], name="cotisations_exercic_a2cefb_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="cotisation",
            constraint=models.UniqueConstraint(
                fields=("membre", "exercice"), name="unicite_cotisation_membre_exercice"
            ),
        ),
        migrations.AddConstraint(
            model_name="cotisation",
            constraint=models.CheckConstraint(
                check=models.Q(("montant_du__gt", 0)), name="montant_du_positif"
            ),
        ),
        migrations.AddConstraint(
            model_name="cotisation",
            constraint=models.CheckConstraint(
                check=models.Q(("montant_paye__gte", 0)),
                name="montant_paye_non_negatif",
            ),
        ),
        migrations.AddConstraint(
            model_name="cotisation",
            constraint=models.CheckConstraint(
                check=models.Q(("montant_paye__lte", models.F("montant_du"))),
                name="paye_inferieur_ou_egal_au_du",
            ),
        ),
        migrations.AddConstraint(
            model_name="exemption",
            constraint=models.UniqueConstraint(
                fields=("membre", "exercice"), name="unicite_exemption_membre_exercice"
            ),
        ),
        migrations.AddConstraint(
            model_name="paiement",
            constraint=models.CheckConstraint(
                check=models.Q(("montant__gt", 0)), name="montant_paiement_positif"
            ),
        ),
    ]
