# Generated by Django 5.0.14 on 2026-09-18 22:17

from django.db import migrations, models


def marquer_cotisations_exemptees_comme_payees(apps, schema_editor):
    """Le concept d'exemption est retiré de l'application (RG, § 5.5.5) : une
    cotisation « Exemptée » n'a plus de statut protecteur après cette
    migration. Sans ce correctif, elle serait recalculée en EN_ATTENTE/
    EN_RETARD au prochain passage du moteur de détection (apps.relances) et
    la personne concernée recommencerait à recevoir des relances — décision
    prise avec la Présidente : ces cotisations sont marquées payées, pas
    supprimées, pour garder une trace de leur montant dans l'historique.
    """
    Cotisation = apps.get_model('cotisations', 'Cotisation')
    for cotisation in Cotisation.objects.filter(statut='EXEMPTEE'):
        cotisation.montant_paye = cotisation.montant_du
        cotisation.statut = 'PAYEE'
        cotisation.save(update_fields=['montant_paye', 'statut'])


class Migration(migrations.Migration):

    dependencies = [
        ('cotisations', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(marquer_cotisations_exemptees_comme_payees,
                             migrations.RunPython.noop),
        migrations.AlterField(
            model_name='cotisation',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PARTIEL', 'Partiellement payée'), ('PAYEE', 'Payée'), ('EN_RETARD', 'En retard')], default='EN_ATTENTE', max_length=12),
        ),
        migrations.DeleteModel(
            name='Exemption',
        ),
    ]
