# Generated by Django 5.2.17 on 2026-09-26 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("membres", "0003_corrige_codes_sections"),
        ("sections", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=150)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("CONFERENCE", "Conférence"),
                            ("FORMATION", "Formation"),
                            ("JOURNEE_SCIENTIFIQUE", "Journée scientifique"),
                            ("ASSEMBLEE_GENERALE", "Assemblée générale"),
                            ("REUNION", "Réunion"),
                            ("AUTRE", "Autre"),
                        ],
                        max_length=25,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("date_debut", models.DateTimeField(verbose_name="début")),
                (
                    "date_fin",
                    models.DateTimeField(blank=True, null=True, verbose_name="fin"),
                ),
                ("lieu", models.CharField(max_length=150)),
                (
                    "places",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Laisser vide si le nombre de participantes n'est pas limité.",
                        null=True,
                        verbose_name="nombre de places",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_PREPARATION", "En préparation"),
                            ("PUBLIEE", "Publiée"),
                            ("TERMINEE", "Terminée"),
                            ("ANNULEE", "Annulée"),
                        ],
                        default="EN_PREPARATION",
                        max_length=15,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifiee_le", models.DateTimeField(auto_now=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activites_creees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        help_text="Laisser vide pour une activité nationale, ouverte à toutes les membres.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activites",
                        to="sections.section",
                    ),
                ),
            ],
            options={
                "verbose_name": "activité",
                "verbose_name_plural": "activités",
                "ordering": ["date_debut"],
            },
        ),
        migrations.CreateModel(
            name="Inscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inscrite_le", models.DateTimeField(auto_now_add=True)),
                (
                    "activite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscriptions",
                        to="activites.activite",
                    ),
                ),
                (
                    "membre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inscriptions",
                        to="membres.membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "inscription",
                "verbose_name_plural": "inscriptions",
            },
        ),
        migrations.CreateModel(
            name="MembreComite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mission",
                    models.CharField(
                        blank=True,
                        help_text="Facultatif : logistique, communication, programme…",
                        max_length=80,
                    ),
                ),
                ("ajoutee_le", models.DateTimeField(auto_now_add=True)),
                (
                    "activite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comite",
                        to="activites.activite",
                    ),
                ),
                (
                    "ajoutee_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "membre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comites",
                        to="membres.membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "membre du comité d'organisation",
                "verbose_name_plural": "comité d'organisation",
            },
        ),
        migrations.AddIndex(
            model_name="activite",
            index=models.Index(
                fields=["statut", "date_debut"], name="activites_a_statut_290025_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="activite",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("date_fin__isnull", True),
                    ("date_fin__gte", models.F("date_debut")),
                    _connector="OR",
                ),
                name="activite_fin_apres_debut",
            ),
        ),
        migrations.AddConstraint(
            model_name="inscription",
            constraint=models.UniqueConstraint(
                fields=("activite", "membre"), name="unicite_inscription"
            ),
        ),
        migrations.AddConstraint(
            model_name="membrecomite",
            constraint=models.UniqueConstraint(
                fields=("activite", "membre"), name="unicite_membre_comite"
            ),
        ),
    ]
