# Generated by Django 5.2.17 on 2026-09-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activites", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activite",
            name="annoncee",
            field=models.BooleanField(
                default=False,
                help_text="Titre, date et lieu seront visibles de tout public une fois l'activité publiée. À laisser décoché pour une réunion interne.",
                verbose_name="annoncer sur la page d'accueil publique",
            ),
        ),
    ]
