# Generated by Django 5.0.14 on 2026-09-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('MEMBRE', 'Membre'), ('RESP_ADMIN', 'Secrétaire générale'), ('RESP_SECTION', 'Coordinatrice de section'), ('RESP_FINANCIER', 'Trésorière'), ('ADMIN', 'Présidente')], default='MEMBRE', max_length=15),
        ),
    ]
