# Generated by Django 5.2.17 on 2026-09-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_responsables_redeviennent_membres"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utilisateur",
            name="role",
            field=models.CharField(
                choices=[
                    ("MEMBRE", "Membre"),
                    ("RESP_ADMIN", "Secrétaire générale"),
                    ("RESP_SECTION", "Coordinatrice de section"),
                    ("RESP_FINANCIER", "Trésorière"),
                    ("RESP_ORGA", "Responsable à l'organisation"),
                    ("ADMIN", "Présidente"),
                ],
                default="MEMBRE",
                max_length=15,
            ),
        ),
    ]
