# Generated by Django 5.0.14 on 2026-09-12 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_operation", models.CharField(max_length=40)),
                ("detail", models.TextField(blank=True)),
                ("adresse_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("horodatage", models.DateTimeField(auto_now_add=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "opération journalisée",
                "verbose_name_plural": "journal des opérations",
                "ordering": ["-horodatage"],
                "indexes": [
                    models.Index(
                        fields=["-horodatage"], name="core_journa_horodat_e4e532_idx"
                    ),
                    models.Index(
                        fields=["type_operation"], name="core_journa_type_op_2845a5_idx"
                    ),
                ],
            },
        ),
    ]
