# Generated by Django 5.0.14 on 2026-09-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("libelle", models.CharField(max_length=100)),
                ("ville", models.CharField(blank=True, max_length=80)),
                ("etablissement", models.CharField(blank=True, max_length=150)),
                ("date_creation", models.DateField(auto_now_add=True)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "section",
                "verbose_name_plural": "sections",
                "ordering": ["libelle"],
            },
        ),
    ]
