# Generated by Django 5.0.14 on 2026-09-12 12:15

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sections", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Membre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "matricule",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenoms", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("telephone", models.CharField(blank=True, max_length=20)),
                ("date_naissance", models.DateField(blank=True, null=True)),
                ("grade", models.CharField(blank=True, max_length=80)),
                ("etablissement", models.CharField(blank=True, max_length=150)),
                ("date_adhesion", models.DateField(default=datetime.date.today)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("ACTIF", "Actif"),
                            ("INACTIF", "Inactif"),
                            ("SUSPENDU", "Suspendu"),
                        ],
                        default="ACTIF",
                        max_length=10,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="membres",
                        to="sections.section",
                    ),
                ),
                (
                    "utilisateur",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fiche_membre",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "membre",
                "verbose_name_plural": "membres",
                "ordering": ["nom", "prenoms"],
                "indexes": [
                    models.Index(
                        fields=["section", "statut"],
                        name="membres_mem_section_9e3145_idx",
                    ),
                    models.Index(
                        fields=["nom", "prenoms"], name="membres_mem_nom_d533d5_idx"
                    ),
                ],
            },
        ),
    ]
