# Generated by Django 5.0.14 on 2026-09-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membres", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membre",
            name="matricule",
            field=models.CharField(
                editable=False,
                max_length=20,
                unique=True,
                verbose_name="n° d'adhérente",
            ),
        ),
    ]
