# Generated by Django 5.2.17 on 2026-09-27 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChiffreCle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valeur",
                    models.CharField(
                        help_text="Ex. « 1 000 », « 17 », « 3ᵉ ».", max_length=20
                    ),
                ),
                (
                    "libelle",
                    models.CharField(
                        help_text="Ex. « membres ».",
                        max_length=60,
                        verbose_name="libellé",
                    ),
                ),
                (
                    "precision",
                    models.CharField(
                        blank=True,
                        help_text="Ex. « en 2024, selon l'UVCI ».",
                        max_length=120,
                        verbose_name="précision / source",
                    ),
                ),
                ("ordre", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "chiffre clé",
                "verbose_name_plural": "chiffres clés",
                "ordering": ["ordre", "pk"],
            },
        ),
        migrations.CreateModel(
            name="Realisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("annee", models.PositiveSmallIntegerField(verbose_name="année")),
                (
                    "periode",
                    models.CharField(
                        blank=True,
                        help_text="Facultatif, ex. « octobre », « mai ».",
                        max_length=40,
                        verbose_name="période",
                    ),
                ),
                ("titre", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="D'où vient l'information (article, publication…).",
                        max_length=150,
                    ),
                ),
                (
                    "publiee",
                    models.BooleanField(
                        default=True, verbose_name="affichée sur la page"
                    ),
                ),
            ],
            options={
                "verbose_name": "réalisation",
                "verbose_name_plural": "réalisations",
                "ordering": ["-annee", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="PageAccueil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accroche", models.CharField(max_length=160)),
                (
                    "sous_titre",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="sous-titre"
                    ),
                ),
                ("presentation", models.TextField(verbose_name="qui sommes-nous")),
                (
                    "mission",
                    models.TextField(
                        blank=True,
                        help_text="Une mission par ligne.",
                        verbose_name="nos missions",
                    ),
                ),
                (
                    "email_contact",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="adresse de contact"
                    ),
                ),
                ("site_institutionnel", models.URLField(blank=True)),
                (
                    "contenu_verifie",
                    models.BooleanField(
                        default=False,
                        help_text="À cocher par la Présidente une fois les textes et les chiffres vérifiés.",
                        verbose_name="contenu relu et validé",
                    ),
                ),
                ("modifiee_le", models.DateTimeField(auto_now=True)),
                (
                    "modifiee_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "page d'accueil",
                "verbose_name_plural": "page d'accueil",
            },
        ),
    ]
