# Generated by Django 5.2.17 on 2026-09-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vitrine", "0002_contenu_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pageaccueil",
            name="presidente_message",
            field=models.TextField(
                blank=True,
                help_text="Quelques lignes de bienvenue, rédigées ou validées par la Présidente.",
                verbose_name="mot de la Présidente",
            ),
        ),
        migrations.AddField(
            model_name="pageaccueil",
            name="presidente_nom",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="nom de la Présidente"
            ),
        ),
        migrations.AddField(
            model_name="pageaccueil",
            name="presidente_photo",
            field=models.BinaryField(blank=True, null=True, verbose_name="photo"),
        ),
        migrations.AddField(
            model_name="pageaccueil",
            name="presidente_photo_maj",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="pageaccueil",
            name="presidente_presentation",
            field=models.TextField(
                blank=True,
                help_text="Parcours et mandat, à la troisième personne, à partir de sources vérifiables.",
                verbose_name="présentation de la Présidente",
            ),
        ),
        migrations.AddField(
            model_name="pageaccueil",
            name="presidente_titre",
            field=models.CharField(
                blank=True,
                default="Présidente de l'AFEMC-CI",
                help_text="Ex. « Présidente de l'AFEMC-CI, Professeure titulaire ».",
                max_length=150,
                verbose_name="titre affiché",
            ),
        ),
    ]
