# Generated by Django 5.2.17 on 2026-09-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vitrine", "0004_presentation_presidente"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhotoGalerie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.BinaryField()),
                ("largeur", models.PositiveIntegerField(default=0, editable=False)),
                ("hauteur", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "legende",
                    models.CharField(
                        blank=True,
                        help_text="Ce que montre la photo : événement, lieu, date. Ne nommer que des personnes qui ont donné leur accord.",
                        max_length=200,
                        verbose_name="légende",
                    ),
                ),
                ("ordre", models.PositiveSmallIntegerField(default=0)),
                (
                    "publiee",
                    models.BooleanField(
                        default=True, verbose_name="affichée sur la page"
                    ),
                ),
                ("ajoutee_le", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "photo de la galerie",
                "verbose_name_plural": "galerie de photos",
                "ordering": ["ordre", "-ajoutee_le"],
            },
        ),
    ]
